# Generated by Django 4.2.6 on 2023-11-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_viewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
